version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  rails:
    build: "."
    volumes:
      - ".:/usr/var/app"
    ports:
      - "3000:3000"
    environment:
      RAILS_DATABASE_USER: "postgres"
      RAILS_DATABASE_PASSWORD: "postgres"
      RAILS_DATABASE_HOST: "postgres"

volumes:
  postgres_data:
    driver: "local"
